<?xml version="1.0" encoding="UTF-8"?>
<definitions
    name=""
    targetNamespace=""
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"

    xmlns:tns="http://package.of.this.service/ThisService.wsdl"
    xmlns:ns1="http://package.of.the.xsd.of.this.service/TypesOfThisService.xsd"
    >

    <!-- only one - could contain multiple rerefences to multiple XSDs though -->
    <!-- defines the data types employed by the service -->
    <!-- contains a <schema> element, which in turn contains -->
    <!-- references to XSD files, simpleType elements complexType elements -->
    <!-- or even just "element" elements -->
    <types></types>

    <!-- one or more -->
    <!-- defines the messages used as input and output by the operations -->
    <!-- exposed by the service -->
    <message></message>

    <!-- one (or more?!) -->
    <!-- defines the interface of the operations exposed by the service -->
    <!-- i.e. for each operation, it defines the input and the output -->
    <portType>
        <!-- one or more -->
        <operation></operation>
    </portType>

    <!-- one or more -->
    <!-- binds each operation defined in the portTypes to an ACTION -->
    <!-- also specifies the behaviour of each operation -->
    <!-- i.e. does it accept an input, does it return an output -->
    <binding>
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <!-- one or more -->
        <operation></operation>
    </binding>

    <!-- one (or more?!) -->
    <!-- for each port type defined above -->
    <!-- it defines a concrete port element -->
    <!-- each port element is linked to a binding defined above -->
    <!-- each port element also defines a location i.e. at which address is the port exposed -->
    <service>
        <!-- one or more -->
        <port></port>
    </service>

</definitions>